import { readFile } from "node:fs/promises";
import { basename, resolve, relative, sep } from "node:path";
import { SCHEMA_VERSION, parseContract, type RequirementContract } from "@specbridge/core";
export type AdapterInput = { path: string; maxBytes?: number };
export interface SpecificationAdapter { name: string; load(input: AdapterInput): Promise<RequirementContract>; }
async function safeRead(input: AdapterInput): Promise<string> { const path = resolve(input.path); if (relative(process.cwd(), path).startsWith(`..${sep}`)) throw new Error("Input must be within the current working directory"); const value = await readFile(path, "utf8"); if (Buffer.byteLength(value) > (input.maxBytes ?? 1_000_000)) throw new Error("Input exceeds the size limit"); return value; }
export class JsonAdapter implements SpecificationAdapter { name = "json"; async load(input: AdapterInput) { return parseContract(JSON.parse(await safeRead(input))); } }
/** Limited Markdown convention: # title, then ## requirement-id: title and - [criterion-id] description. */
export class MarkdownAdapter implements SpecificationAdapter { name = "markdown"; async load(input: AdapterInput) { const raw = await safeRead(input); const lines = raw.split(/\r?\n/); const title = lines.find((line) => line.startsWith("# "))?.slice(2).trim(); if (!title) throw new Error("Markdown requires a '# title' heading"); const requirements: RequirementContract["requirements"] = []; let current: RequirementContract["requirements"][number] | undefined; lines.forEach((line, index) => { const requirement = /^##\s+([A-Za-z0-9._:-]+):\s+(.+)$/.exec(line); if (requirement) { current = { id: requirement[1]!, title: requirement[2]!, description: requirement[2]!, criteria: [], source: { type: "markdown", path: input.path.replaceAll("\\", "/"), startLine: index + 1 } }; requirements.push(current); return; } const criterion = /^-\s+\[([A-Za-z0-9._:-]+)\]\s+(.+)$/.exec(line); if (criterion && current) current.criteria.push({ id: criterion[1]!, description: criterion[2]! }); }); if (!requirements.length || requirements.some((requirement) => !requirement.criteria.length)) throw new Error("Each Markdown requirement needs a criterion: '- [criterion-id] description'"); return parseContract({ schemaVersion: SCHEMA_VERSION, id: basename(input.path).replace(/\.[^.]+$/, ""), title, source: { type: "markdown", path: input.path.replaceAll("\\", "/") }, requirements }); } }
/** Supports Fission-AI OpenSpec's current `openspec/specs/<capability>/spec.md` Markdown subset. */
export class OpenSpecAdapter extends MarkdownAdapter { name = "openspec"; override async load(input: AdapterInput) { if (!input.path.replaceAll("\\", "/").includes("openspec/specs/")) throw new Error("OpenSpec input must be an openspec/specs/<capability>/spec.md file"); return super.load(input); } }
export const adapters: Record<string, SpecificationAdapter> = { json: new JsonAdapter(), markdown: new MarkdownAdapter(), openspec: new OpenSpecAdapter() };
